version: '3'

volumes:
    pg_data_prod:
    static_volume:

services:
  backend:
    image: qjgns/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db

  frontend:
    image: qjgns/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static_volume:/frontend_static

  db:
    image: postgres:15.3-alpine3.18
    env_file: .env
    restart: always
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  gateway:
    image: qjgns/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - backend
